### ISSUE TITLE
[Bug] Suspected Regression from 0.4.5 --> 0.4.6; "Error: auth_token need to be set of auth_username and auth_password"

### ISSUE THREAD

**Issue by brettpalmberg** [rundeck/terraform-provider-rundeck#110] opened 2023-10-13 17:59 UTC
### Terraform Version

Terraform v1.5.5
provider registry.terraform.io/rundeck/rundeck v0.4.6

### Affected Resource(s)

Rundeck provider using "auth_token". The auth_token value is provided via module output. This works if the rundeck provider is pinned to previous version 0.4.5 or earlier.

Example:
```
provider "rundeck" {
  url         = module.rundeck.url
  api_version = "41"
  auth_token  = module.rundeck.auth_token
}
```

### Debug Output

2023-10-13T13:45:07.825-0400 [ERROR] vertex "provider[\"registry.terraform.io/rundeck/rundeck\"]" error: auth_token need to be set of auth_username and auth_password

### Expected Behavior

Clean `terraform plan` without errors.

### Actual Behavior

Error in `terraform plan`:
```
error: auth_token need to be set of auth_username and auth_password
```
### Steps to Reproduce
`terraform plan`

### Important Factoids
NA

### References
I think this may be related to the PR here: https://github.com/rundeck/terraform-provider-rundeck/pull/103/files 

Thank you.

**Comment by fdevans** [comment] 2023-10-23 17:15
Can you provide more details here?  I was not able to reproduce this with my environment and 0.4.6.  I am able to run my plan using just an `auth_token` specified.

**Comment by brettpalmberg** [comment] 2023-10-26 16:33
Thank you @fdevans .  I wonder if this occurs when auth_token is provided as an output of another module (rather than an explicit string in the provider block)?

**Comment by fdevans** [comment] 2023-10-26 16:59
I thought that too, but I built my test environment that way and it also works as expected.

**Comment by brettpalmberg** [comment] 2023-10-26 19:32
Thanks. I will see if there is any additional information I can glean from the debug logging.

**Comment by DriesdeKort** [comment] 2023-12-21 12:26
I have the same problem in version 0.4.7

**Comment by fdevans** [comment] 2024-09-21 01:43
Thanks @DriesdeKort -   Feel free to submit a Pull Request if you think the error message can be clearer.

@brettpalmberg - if there isn't any further logs I'm gonna close this

**Closed** 2024-09-24 16:46 UTC
Labels: waiting-response
